# Generated by Django 3.1.7 on 2021-03-11 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 22, 10, 31, 766053)),
        ),
    ]
