# Generated by Django 3.1.7 on 2021-03-12 06:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_manager', '0002_employe_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 11, 51, 21, 887070)),
        ),
        migrations.CreateModel(
            name='ChildEmploye',
            fields=[
                ('ChildSno', models.AutoField(primary_key=True, serialize=False)),
                ('parentEmploye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.employe')),
            ],
        ),
    ]
