# Generated by Django 3.1.7 on 2021-03-12 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_manager', '0003_auto_20210312_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='childemploye',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 15, 45, 22, 821230)),
        ),
    ]
