# Generated by Django 3.1.7 on 2021-03-12 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_manager', '0004_auto_20210312_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 15, 45, 50, 223284)),
        ),
    ]
